<?php
define("_NOM", "NOMBRE");
define("_BUSCAR", "Nº BUSQUEDAS");
define("_COMP", "COMPETENCIA");
define("_TPAG", "TOTAL DE PÁGINAS");
define("_POS", "POSICIÓN");
define("_POSP", "POSICIÓN PREV.");
define("_PREU", "PRECIO");
define("_TRAFIC", "TRÁFICO");
define("_PROD", "PRODUCTO");
define("_REF", "REFERENCIA");
define("_VIST", "NÚMERO DE PRODUCTOS");
define("_LMaVe", "LO MÁS VENDIDO");
define("_LMaVe30", "LO MÁS VENDIDO últimos 30 dias");
define("_LMaVi", "PALABRAS MÁS BUSCADAS");
define("_LMaVi30", "PALABRAS MÁS BUSCADAS últimos 30 dias");
define("_LMenVe", "LO MENOS VENDIDO");
define("_Title", "INFORME SEO Y MARKETING");
define("_Web", "PÁGINA WEB: ");
define("_NUM", "NÚMERO DE REPETICIONES");
define("_MeBusc", "MENOS BUSCADOS");
define("_MaBusc", "MÁS BUSCADOS");
define("_MaBusc30", "MÁS BUSCADOS últimos 30 dias ");
define("_NoRes", "SIN RESULTADOS");
define("_NoRes30", "SIN RESULTADOS últimos 30 dias");
define("_Ventas", "VENTAS");
define("_User", "USUARIO");
define("_Visitas", "VISITAS");
define("_Session", "SESIÓN");
define("_Rebot", "REBOTE");
define("_New", "NUEVO");
define("_Time", "TIEMPO MEDIO");
define("_Conv", "CONVERSIÓN");
?>